### ISSUE TITLE
Clock: New must return a pointer

### ISSUE THREAD

**Issue by TatriX** [exercism/xgo#126] opened 2015-01-30 08:58 UTC
The "Clock" exercise wants ```New()``` to return non pointer value and it's wrong in my opinion.
```New()``` must return a pointer or a value which represents pointer like reflect.Value
So if:
```go
c1 := New()
c2 := New()
```
```c1``` cannot be equal to ```c2``` because it's different pointers.

**Comment by soniakeys** [comment] 2015-01-30 13:03
Working as intended.  See issue https://github.com/exercism/xgo/issues/123.

In PR https://github.com/exercism/xgo/pull/125 I explained that I didn't think TestVersion needed to be bumped, but maybe it should be bumped after all, so we could know if the solver has the new error message and comments available.

As to whether a function named New should always return a pointer, I just posted to the go-nuts mailing list asking for opinion.  It should be interesting.  If the verdict is that a non-pointer New is bad style, I propose renaming our function something like Time or HourMinute.  I'll still be opposed to changing it to return a pointer.

**Comment by soniakeys** [comment] 2015-01-31 13:03
Huh.  The response was a little disappointing.  Sometimes on issues of style like this people more eagerly voice their opinions.  Out of 95 views, only four people felt compelled to post.  A couple of the responses were a bit tangential, but none said that New should return a pointer, none said that a constructor that returns a non-pointer should not be named New.

I'm still most inclined to leave this as "working as intended."

**Comment by TatriX** [comment] 2015-01-31 14:02
greping through the standard library shoes that New*() funcs return
1) *struct
2) interface
3) *struct, error
4) interface, error
On the other side structs having non-pointer receivers do not have a New() func and rather have alternative constructors like time.Unix()

**Comment by kytrinyx** [comment] 2015-01-31 17:02
Even though this is not clear-cut, I find it interesting that we can't find an example in the standard library where a `New()` function returns a non-pointer (aside from interface, which is different).

I'm inclined to follow that unspoken pattern.

**Comment by soniakeys** [comment] 2015-01-31 21:24
I'm not sure I understand.  What unspoken pattern?

**Comment by kytrinyx** [comment] 2015-01-31 21:54
The idea that `New()` would probably return a pointer, and to call a constructor that returns a value something else.

I don't feel strongly about it, but I lean slightly towards that side of the argument.

**Comment by soniakeys** [comment] 2015-01-31 22:13
Okay.  PR soon.

**Comment by kytrinyx** [comment] 2015-01-31 23:29
Fixed in #127

**Closed by kytrinyx** 2015-01-31 23:29 UTC
