### ISSUE TITLE
difference-of-squares test has no targetTestVersion

### ISSUE THREAD

**Issue by tleen** [exercism/xgo#465] opened 2017-01-26 21:05 UTC
[The test for difference-of-squares](https://github.com/exercism/xgo/blob/master/exercises/difference-of-squares/difference_of_squares_test.go) currently does not use the targetTestVersion const to sync up solutions with the tests. I believe a few others do not either. Should all the exercises be using these or is it the sort of thing that you only start using on a second version of a test?

**Comment by petertseng** [comment] 2017-01-27 05:27
I'll defer to the README's https://github.com/exercism/xgo#problem-versioning section on this point, added in #140 . It says

> Each problem defines a `const targetTestVersion` in the test program

Since it does say "each", then it would appear that any problem that fails to define a `targetTestVersion` is in violation of the README.

Assuming we agree with the reasoning for having test versions (this is someone's opportunity to speak up, if you think they are not useful), they should be added or the sentence in the README should be changed.

**Comment by robphoenix** [comment] 2017-01-27 08:04
I'd lean towards all exercises starting from a point of having a targetTestVersion that can be incremented as necessary.

**Comment by tleen** [comment] 2017-01-27 13:07
The point of it is to sync up the exercise with the test to ensure we don't have users running their source file against a test that may cause incorrect fails or passes?

This looks like the kind of thing that may have been dropped then starter files we not provided with the exercises? 

I can see an argument that if there has been no change to the test than the test version doesn't have to be checked (or is implicitly at 0), and if you change the initial test then you have to start using the targetTestVersion at 1. 

Either way it is inconsistent in the code base and should probably be brought into alignment across the exercises. Either explicitly not needing it for the first version or requiring it across the board.

**Comment by robphoenix** [comment] 2017-01-27 15:34
I agree, it should certainly be consistent across all the exercises. I think starting each exercise off with a `testVersion`, whether 1 or 0, is better than not having one, as the intention is to use it if there is ever a significant change to the exercise or it's tests. It's an indication there is some mechanism in place for accommodating changes to tests, rather than it coming into play only if there is a change.
I think this will also cause less confusion regarding some exercises having a `testVersion` and some not.

**Comment by tleen** [comment] 2017-01-27 15:45
I can agree with that, explicit better than implicit.

**Comment by tleen** [comment] 2017-01-28 13:38
I can get on adding all the test vars if if what we want to do.

**Comment by robphoenix** [comment] 2017-01-28 17:08
Are you happy with this @petertseng?

**Comment by petertseng** [comment] 2017-01-28 19:52
Yup, we'd be glad to have them!

**Comment by robphoenix** [comment] 2017-01-28 22:57
Good stuff, thanks for making this happen @tleen

**Comment by tleen** [comment] 2017-01-28 23:29
Ok will do!

**Comment by tleen** [comment] 2017-01-30 01:34
I noticed some inconsistency in the location for test version test. If there are no objections I will move the test version test function to be the first function in the test file, and keep the benchmark (where available) as the last?

**Comment by petertseng** [comment] 2017-01-30 01:45
>  If there are no objections I will move the test version test function to be the first function in the test file

@kytrinyx spoke about this October:

* https://github.com/exercism/xgo/pull/401#discussion_r83198176
* https://github.com/exercism/xgo/pull/403#discussion_r83205896
* https://github.com/exercism/xgo/pull/404#discussion_r83207256

We could change that if we agreed to.

For the record, I have no argument to argue for either side, do as y'all wish.

**Comment by petertseng** [comment] 2017-01-30 01:47
... but in the absence of strong argument to the contrary, I would stick with the precedent set by Katrina.

**Comment by tleen** [comment] 2017-01-30 02:41
OK will keep at bottom as @kytrinyx did, her reasoning is as good as any. I'll move any not at the bottom as part of this overhaul.

**Comment by petertseng** [comment] 2017-01-30 02:48
OK.

I had a question on whether "bottom" meant "below benchmarks" or "above benchmarks, but below all other non-benchmark tests" - #403 shows it as below benchmarks, I don't know if I have any other examples.

Note (don't know if you would or would not have done this without my saying it), it would probably be best for the sanity of the reviewers if a commit of "move all testTestVersion to bottom" were separate from a commit of "add testTestVersion to exercises that don't already have it".

**Comment by kytrinyx** [comment] 2017-01-30 03:04
Oh. I would put it above the benchmarks.

**Comment by robphoenix** [comment] 2017-01-30 09:13
Does this also include moving the version tests out of the main test function as it is in some exercises (https://github.com/exercism/xgo/blob/master/exercises/allergies/allergies_test.go#L27)
Personally I think it's probably better to have the version test separate.

And one more thing, some of the version tests fail with `Errorf`, and some with `Fatalf`. As we're going for consistency here, maybe we should stick to the same for all exercises. My choice would be on `Fatalf` as I don't think there's any point in carrying on if there's a mismatch?

**Comment by tleen** [comment] 2017-01-30 11:54
Yes I think we move to its own function with Fatalf.

Order should be:
- specific tests
- test version test
- benchmark (if exists)

**Comment by tleen** [comment] 2017-01-30 12:14
Would you rather see this committed monolithically: adding all the testversions for all exercises in one commit, then doing the functions for all of them as another? 

Or would it be better to do all the necessary changes on a single exercise to bring it up to snuff and commit it on a per exercise basis? Looks like most of them will need some sort of update to get in sync with the rest.

**Comment by robphoenix** [comment] 2017-01-30 12:45
I would do it per exercise, if you're updating particular files you might as well make all the changes needed.

Just one question before we get going on this. I understand the reasoning behind putting the `TestTestVersion` function after the exercise specific tests;
> to keep it out of the way for the person reading it.

This though means that any exercise tests will be run before this version test, resulting in a test output showing failed exercise tests before a version mismatch, rather than the version mismatch shutting down the test suite before running tests that could be erroring due to this mismatch. Shouldn't the first test to pass be the one that is making sure you're running the correct tests for the exercise?

**Comment by tleen** [comment] 2017-01-30 12:50
Visually that is how is reads, but I believe GO tests run in parallel. So location in this case doesn't matter. Moving it to the top would be more like a "Hey! This is an easy way it could fail look here first", but keeping it out of the way makes sense too.

**Comment by robphoenix** [comment] 2017-01-30 13:24
So, after a little [digging](https://gophers.slack.com/archives/general/p1485781892036688), it appears tests within a single package are run sequentially, unless marked with [`t.Parallel()`](https://golang.org/pkg/testing/#T.Parallel), therefore is it worth ensuring the test version is correct before running any specific exercise tests?
What do you think @petertseng @kytrinyx ?

**Comment by tleen** [comment] 2017-01-30 17:09
Looks like this has been subsumed into #470?

**Comment by robphoenix** [comment] 2017-01-30 17:12
Sorry, I meant to mention something, I think we can keep this open until we've confirmed where we want to put the `TestTestVersion` functions, and `difference-of-squares` has been updated. I've opened up #470 just to have a place to keep track of all the exercises, and progress on updating each exercises test file.

**Comment by petertseng** [comment] 2017-01-31 09:33
My mental model of how the test version is used is that it's for the benefit of those reviewing the exercise once it is submitted. If I'm completing an exercise I don't think it matters much to me whether the version check comes first or last. Maybe y'all feel differently, so please share your experiences if you have any.

However, I will make this observation of https://github.com/exercism/xgo/pull/403#discussion_r83205896:

> The tests execute in parallel, so it doesn't technically matter where it is

Given that y'all have discovered at https://github.com/exercism/xgo/issues/465#issuecomment-276061377 that they tests don't execute in parallel, does that change the premises on which the recommendation to put it at the bottom is made?

**Comment by robphoenix** [comment] 2017-01-31 09:57
I think 9 times out of 10 it's not going to matter at all where this test is, and therefore having it towards the bottom is preferable. My concern is that 1 time a student spends their time trying to solve a problem that is down to a version mismatch rather than their code, frustration that would be avoided by the mismatch highlighted before the failing exercise tests.

Saying this though I'm happy to leave the version test towards the bottom and revisit this if necessary if it's highlighted by students as causing the problem I've outlined above.

I think I'm maybe making a mountain out of a molehill here, and for the time being we should leave it as @tleen describes [here](https://github.com/exercism/xgo/issues/465#issuecomment-276044686)

**Comment by tleen** [comment] 2017-01-31 12:38
@robphoenix that was my original thinking if the tests were running sequentially. Having a mismatch between the exercise solution and the tests could cause false negatives which would be awful for a person learning the language. Better to have the fact that somehow the test and the solution are potentially not compatible fail loud and clear ASAP.

**Comment by robphoenix** [comment] 2017-01-31 13:04
Ok then, I don't think this is a little thing, once someone has read a few exercise test files with the `TestTestVersion` function at the beginning it will hopefully become so familiar as to be invisible, and will avoid much frustration.
So, unless there are any objections, let's put it up at the top of the test file.
I'll update #470 and if you want to submit a PR to close this issue @tleen?

**Comment by tleen** [comment] 2017-01-31 13:29
Sure, I think #470 has been absorbed into this bigger overhaul. I'll probably do it on a per exercise basis?

**Comment by robphoenix** [comment] 2017-01-31 14:25
Aye, that'd be grand, thanks.
Obviously don't feel you have to tackle all of them, or even any of them! #470 should enable this to be done as we go, with anyone pitching in as they are able and willing to.
Really appreciate this @tleen

**Closed by robphoenix** 2017-01-31 14:25 UTC

**Comment by tleen** [comment] 2017-01-31 14:36
Sounds good, will PR the first one as sort of the how-it-should-be-done example then bring the rest up to be consistent with that one.
